name: Bridgecrew
on:
  pull_request:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with: api-key: ${{ secrets.BC_API_KEY }}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!


